source "https://rubygems.org"

gem "lita"

gem "foreman"

# Uncomment to use the HipChat adapter
# gem "lita-hipchat"
gem "lita-slack"

# Uncomment to use the IRC adapter
# gem "lita-irc"

# Add handlers to give Lita new functionality.
# For example:
# gem "lita-google-images"
# gem "lita-karma"
gem "lita-parrot", path: "handlers/lita-parrot"
gem "lita-slack-watch", path: "handlers/lita-slack-watch"
